------------------------------------------------------------------
-- Configuration options for scripted systems in this pack
------------------------------------------------------------------
-- AUTOTRACKER_ENABLE_ITEM_TRACKING = true -- Mostly working
-- AUTOTRACKER_ENABLE_ITEM_TRACKING = false -- Mostly working
